Repository techieOrganization/techie, pull requests merged in 2024-10, with the labels that each got.

#7 [BE] [#4] 카테고리 별 영상 조회 구현 완료 및 충돌 해결
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/com.techie.backend.main.iml
  .idea/sqldialects.xml
  .idea/vcs.xml
  back-end/.gitignore
  back-end/build.gradle
  back-end/src/main/java/com/techie/backend/global/config/ObjectMapperConfig.java
  back-end/src/main/java/com/techie/backend/global/config/RestClientConfig.java
  back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
  back-end/src/main/java/com/techie/backend/video/controller/VideoController.java
  back-end/src/main/java/com/techie/backend/video/domain/Category.java
  back-end/src/main/java/com/techie/backend/video/domain/Video.java
  back-end/src/main/java/com/techie/backend/video/dto/VideoResponse.java
  back-end/src/main/java/com/techie/backend/video/repository/VideoRepository.java
  back-end/src/main/java/com/techie/backend/video/service/VideoService.java
  back-end/src/main/resources/application.yaml
  back-end/src/main/resources/db/data.sql
Labels: ✨ Feature, 🔧 Refactor

#9 [FE] [#10] 페이지 라우팅
  README.md
  front-end/package-lock.json
  front-end/package.json
  front-end/src/app/categories/[id]/page.tsx
  front-end/src/app/favicon.ico
  front-end/src/app/globals.css
  front-end/src/app/gpt-histories/page.tsx
  front-end/src/app/layout.tsx
  front-end/src/app/login/page.tsx
  front-end/src/app/memo/page.tsx
  front-end/src/app/page.module.css
  front-end/src/app/page.tsx
  front-end/src/app/playlists/[id]/page.tsx
  front-end/src/app/playlists/page.tsx
  front-end/src/app/search-histories/page.tsx
  front-end/src/app/signup/page.tsx
  front-end/src/app/watch-histories/page.tsx
  front-end/yarn.lock
Labels: ✨ Feature

#12 [#11] PR 템플릿 관련 이슈 항목 추가
  .github/pull_request_template.md
Labels: 🔧 Refactor

#15 [BE] [#14] 영상 전체 검색 기능 개발 완료
  .idea/encodings.xml
  back-end/build.gradle
  back-end/src/main/java/com/techie/backend/video/controller/VideoController.java
  back-end/src/main/java/com/techie/backend/video/repository/VideoRepository.java
  back-end/src/main/java/com/techie/backend/video/service/VideoService.java
Labels: ✨ Feature

#18 [FE] [#13] 프론트 메인 퍼블리싱 진행
  front-end/.eslintrc.json
  front-end/.prettierrc
  front-end/labels.json
  front-end/package.json
  front-end/public/assets/fonts/GeistMonoVF.woff
  front-end/public/assets/fonts/GeistVF.woff
  front-end/public/assets/images/main/dev_01.png
  front-end/public/assets/images/main/dev_02.png
  front-end/public/assets/images/main/dev_03.png
  front-end/public/assets/images/main/dev_04.png
  front-end/public/assets/images/main/dev_05.png
  front-end/public/assets/images/main/dev_06.png
  front-end/public/assets/images/main/dev_07.png
  front-end/public/assets/images/main/dev_08.png
  front-end/public/assets/images/main/dev_09.png
  front-end/public/assets/images/main/logo01.jpg
  front-end/public/assets/images/main/logo02.jpg
  front-end/public/assets/images/main/logo03.jpg
  front-end/public/assets/images/main/logo04.jpg
  front-end/public/assets/images/main/logo05.jpg
  front-end/src/app/layout.tsx
  front-end/src/app/page.tsx
  front-end/src/components/Footer.tsx
  front-end/src/components/Header.tsx
  front-end/src/data/studentData.js
  front-end/src/libs/api/youtubeAPI.ts
  front-end/src/styles/common/abstracts/_mixins.scss
  front-end/src/styles/common/abstracts/_responsive.scss
  front-end/src/styles/common/base/_font.scss
  front-end/src/styles/common/base/_reset.scss
  front-end/src/styles/common/common.scss
  front-end/src/styles/common/components/_buttons.scss
  front-end/src/styles/common/components/_colors.scss
  front-end/src/styles/common/layout/_footer.scss
  front-end/src/styles/common/layout/_grid.scss
  front-end/src/styles/common/layout/_header.scss
  front-end/src/styles/pages/home/home.scss
  front-end/yarn.lock
Labels: ✨ Feature, 🔗 API, 🎨 UI

#30 [BE] [#6] GPT 기능 추가
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/encodings.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/com.techie.backend.main.iml
  .idea/sqldialects.xml
  .idea/techie.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  back-end/build.gradle
  back-end/src/main/java/com/techie/backend/gpt/controller/GptController.java
  back-end/src/main/java/com/techie/backend/gpt/domain/Gpt.java
  back-end/src/main/java/com/techie/backend/gpt/dto/GptRequest.java
  back-end/src/main/java/com/techie/backend/gpt/dto/GptResponse.java
  back-end/src/main/java/com/techie/backend/gpt/repository/GptRepository.java
  back-end/src/main/java/com/techie/backend/gpt/repository/GptRepositoryCustom.java
  back-end/src/main/java/com/techie/backend/gpt/repository/GptRepositoryImpl.java
  back-end/src/main/java/com/techie/backend/gpt/service/GptService.java
  back-end/src/main/java/com/techie/backend/gpt/service/GptServiceImpl.java
  back-end/src/main/java/com/techie/backend/gpt_history/domain/GptHistory.java
Labels: ✨ Feature, 🔧 Refactor

#33 [BE] [#23] VideoService 코드 리팩토링
  back-end/src/main/java/com/techie/backend/video/controller/VideoController.java
  back-end/src/main/java/com/techie/backend/video/service/VideoService.java
Labels: 🔧 Refactor

#32 [BE] [#31] webConfig 추가
  back-end/src/main/java/com/techie/backend/global/config/WebConfig.java
Labels: ✨ Feature

#39 [BE] [#35] 로그인에 성공한 유저의 정보 조회, 수정, 탈퇴 기능 추가
  back-end/src/main/java/com/techie/backend/global/config/ModelMapperConfig.java
  back-end/src/main/java/com/techie/backend/global/security/CustomUserDetailService.java
  back-end/src/main/java/com/techie/backend/global/security/CustomUserDetails.java
  back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
  back-end/src/main/java/com/techie/backend/user/controller/UserController.java
  back-end/src/main/java/com/techie/backend/user/domain/User.java
  back-end/src/main/java/com/techie/backend/user/dto/UserRequest.java
  back-end/src/main/java/com/techie/backend/user/dto/UserResponse.java
  back-end/src/main/java/com/techie/backend/user/repository/UserRepositoryImpl.java
  back-end/src/main/java/com/techie/backend/user/service/UserService.java
  back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
Labels: ✨ Feature, 🔧 Refactor

#44 [BE] [#42] 스프링 시큐리티 설정
  back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
Labels: 🔧 Refactor

#48 [BE] refactor: config 설정 복구
  back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
Labels: 🔧 Refactor

#50 [BE ] CORS 에러 해결을 위한 테스트
  back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
  back-end/src/main/java/com/techie/backend/user/controller/UserController.java
  back-end/src/main/java/com/techie/backend/user/domain/User.java
  back-end/src/main/java/com/techie/backend/user/dto/UserRequest.java
  back-end/src/main/java/com/techie/backend/user/dto/UserResponse.java
  back-end/src/main/java/com/techie/backend/user/service/UserService.java
  back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
Labels: 🧪 Test

#57 [FE] [#56] 프론트 husky 문제 해결
  .husky/pre-commit
  front-end/.husky/pre-commit
Labels: 🐛 Bug

#55 [FE] [#37] 마이페이지 퍼블리싱
  front-end/src/app/mypage/page.tsx
  front-end/src/styles/common/layout/_grid.scss
  front-end/src/styles/pages/mypage/mypage.scss
Labels: ✨ Feature, 🎨 UI
