Repository techieOrganization/techie, pull requests merged in 2024-11, with the labels that each got.

#40 [FE] [#13] 메인 프론트 레이아웃 수정
  front-end/public/assets/images/main/memoji01.webp
  front-end/public/assets/images/main/memoji02.webp
  front-end/public/assets/images/main/memoji03.webp
  front-end/public/assets/images/main/memoji04.webp
  front-end/public/assets/images/main/memoji05.webp
  front-end/public/assets/images/main/memoji06.webp
  front-end/public/assets/images/main/memoji07.webp
  front-end/public/assets/images/main/memoji08.webp
  front-end/public/assets/images/main/memoji09.webp
  front-end/public/assets/images/main/memoji10.webp
  front-end/src/app/page.tsx
  front-end/src/data/studentData.js
  front-end/src/styles/pages/home/home.scss
Labels: 🎨 UI

#41 [FE] [#38] 회원가입 백엔드 연결 / 환경 변수 설정
  front-end/@types/global.d.ts
  front-end/next.config.mjs
  front-end/package-lock.json
  front-end/package.json
  front-end/src/app/login/page.tsx
  front-end/src/app/signup/page.tsx
  front-end/src/libs/api/registerUserApi.ts
  front-end/src/styles/common/components/_colors.scss
  front-end/src/styles/pages/login/login.scss
  front-end/src/styles/pages/register/register.scss
  front-end/tsconfig.json
  front-end/yarn.lock
Labels: ✨ Feature, 🔗 API, 🎨 UI

#61 [BE] 시큐리티 로그인 응답 JSON 타입으로 반환 문제 해결
  back-end/build.gradle
  back-end/src/main/java/com/techie/backend/global/config/ModelMapperConfig.java
  back-end/src/main/java/com/techie/backend/global/config/ObjectMapperConfig.java
  back-end/src/main/java/com/techie/backend/global/security/CustomUserDetailService.java
  back-end/src/main/java/com/techie/backend/global/security/CustomUserDetails.java
  back-end/src/main/java/com/techie/backend/global/security/JWTFilter.java
  back-end/src/main/java/com/techie/backend/global/security/JWTUtil.java
  back-end/src/main/java/com/techie/backend/global/security/LoginFilter.java
  back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
  back-end/src/main/java/com/techie/backend/global/security/UserDetailsCustom.java
  back-end/src/main/java/com/techie/backend/global/security/UserDetailsServiceCustom.java
  back-end/src/main/java/com/techie/backend/user/controller/UserController.java
  back-end/src/main/java/com/techie/backend/user/domain/User.java
  back-end/src/main/java/com/techie/backend/user/dto/UserRequest.java
  back-end/src/main/java/com/techie/backend/user/dto/UserResponse.java
  back-end/src/main/java/com/techie/backend/user/repository/UserRepository.java
  back-end/src/main/java/com/techie/backend/user/repository/UserRepositoryCustom.java
  back-end/src/main/java/com/techie/backend/user/repository/UserRepositoryImpl.java
  back-end/src/main/java/com/techie/backend/user/service/UserService.java
  back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
Labels: ✨ Feature, 🔧 Refactor, 🧪 Test

#68 [BE] [#67] JWT 관련 필터와 getEmail 수정
  back-end/src/main/java/com/techie/backend/global/security/JWTFilter.java
  back-end/src/main/java/com/techie/backend/global/security/JWTUtil.java
Labels: 🐛 Bug

#69 [BE] [#28] 회원 정보 조회 , 수정 , 탈퇴 기능 추가
  back-end/src/main/java/com/techie/backend/global/security/JWTFilter.java
  back-end/src/main/java/com/techie/backend/global/security/JWTUtil.java
  back-end/src/main/java/com/techie/backend/global/security/LoginFilter.java
  back-end/src/main/java/com/techie/backend/global/security/UserDetailsCustom.java
  back-end/src/main/java/com/techie/backend/global/security/UserDetailsServiceCustom.java
  back-end/src/main/java/com/techie/backend/user/controller/UserController.java
  back-end/src/main/java/com/techie/backend/user/domain/User.java
  back-end/src/main/java/com/techie/backend/user/dto/UserRequest.java
  back-end/src/main/java/com/techie/backend/user/dto/UserResponse.java
  back-end/src/main/java/com/techie/backend/user/repository/UserRepository.java
  back-end/src/main/java/com/techie/backend/user/service/UserService.java
  back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
Labels: ✨ Feature, 🧪 Test

#72 [FE] [65] NextAuth를 사용한 로그인 인증절차
  front-end/@types/next-auth.d.ts
  front-end/package.json
  front-end/src/app/api/auth/[...nextauth]/route.tsx
  front-end/src/app/api/registerUserApi.ts
  front-end/src/app/api/youtubeAPI.ts
  front-end/src/app/layout.tsx
  front-end/src/app/login/page.tsx
  front-end/src/app/page.tsx
  front-end/src/app/signup/page.tsx
  front-end/src/libs/cookie.ts
  front-end/src/redux/action.ts
  front-end/src/redux/reducer.ts
  front-end/src/redux/store.ts
  front-end/src/redux/types.ts
  front-end/tsconfig.json
  front-end/yarn.lock
Labels: ✨ Feature, 🔗 API

#71 [BE] [#45] gpt 서비스 리팩토링
  back-end/src/main/java/com/techie/backend/global/security/LoginFilter.java
  back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
  back-end/src/main/java/com/techie/backend/global/security/UserDetailsCustom.java
  back-end/src/main/java/com/techie/backend/gpt/controller/GptController.java
  back-end/src/main/java/com/techie/backend/gpt/domain/Gpt.java
  back-end/src/main/java/com/techie/backend/gpt/dto/GptRequest.java
  back-end/src/main/java/com/techie/backend/gpt/dto/GptResponse.java
  back-end/src/main/java/com/techie/backend/gpt/service/GptService.java
  back-end/src/main/java/com/techie/backend/gpt/service/GptServiceImpl.java
Labels: 🔧 Refactor

#77 [BE] [#76] User 유효성 검사 추가
  back-end/src/main/java/com/techie/backend/global/exception/ExceptionType.java
  back-end/src/main/java/com/techie/backend/global/exception/GlobalExceptionHandler.java
  back-end/src/main/java/com/techie/backend/global/exception/user/EmptyFieldException.java
  back-end/src/main/java/com/techie/backend/global/exception/user/InvalidEmailFormatException.java
  back-end/src/main/java/com/techie/backend/global/exception/user/PasswordMismatchException.java
  back-end/src/main/java/com/techie/backend/global/exception/user/PasswordTooShortException.java
  back-end/src/main/java/com/techie/backend/global/exception/user/UserAlreadyExistsException.java
  back-end/src/main/java/com/techie/backend/global/exception/user/UserNotFoundException.java
  back-end/src/main/java/com/techie/backend/global/security/LoginFilter.java
  back-end/src/main/java/com/techie/backend/user/dto/UserRequest.java
  back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
Labels: 🔧 Refactor

#79 [BE] [#78] Video pk 변경 및 Category 추가
  back-end/src/main/java/com/techie/backend/video/domain/Category.java
  back-end/src/main/java/com/techie/backend/video/domain/Video.java
  back-end/src/main/java/com/techie/backend/video/service/VideoService.java
  back-end/src/main/resources/db/data.sql
Labels: 🔧 Refactor

#75 [FE] [#73] 로그인 후 쿠키에 token 값 저장 로직 추가 / 토큰 사용자 정보 리덕스에 저장
  front-end/package-lock.json
  front-end/package.json
  front-end/src/app/layout.tsx
  front-end/src/app/login/page.tsx
  front-end/src/app/mypage/page.tsx
  front-end/src/app/signup/page.tsx
  front-end/src/components/ClientProvider.tsx
  front-end/src/components/Header.tsx
  front-end/src/libs/cookie.ts
  front-end/src/redux/action.ts
  front-end/src/redux/reducer.ts
  front-end/src/redux/store.ts
  front-end/src/types/js-cookie.d.ts
  front-end/src/types/userInfo.d.ts
  front-end/tsconfig.json
  front-end/yarn.lock
Labels: ✨ Feature, 🔧 Refactor

#62 [FE] [#60] 영상 목록 유튜브 리스트 노출 페이지 추가
  front-end/.eslintrc.json
  front-end/@types/next-auth.d.ts
  front-end/next.config.mjs
  front-end/public/assets/images/main/dev_10.png
  front-end/public/assets/images/main/logo06.jpg
  front-end/public/assets/json/videos.json
  front-end/src/app/api/auth/[...nextauth]/route.tsx
  front-end/src/app/api/memoAPI.ts
  front-end/src/app/api/teacherAPI.ts
  front-end/src/app/api/videoAPI.ts
  front-end/src/app/api/videoAPIDetail.ts
  front-end/src/app/api/youtubeAPI.ts
  front-end/src/app/login/page.tsx
  front-end/src/app/page.tsx
  front-end/src/app/playlists/[category]/[videoId]/page.tsx
  front-end/src/app/playlists/[category]/page.tsx
  front-end/src/app/playlists/[id]/page.tsx
  front-end/src/app/playlists/page.tsx
  front-end/src/app/teacher-lists/[category]/page.tsx
  front-end/src/app/teacher-lists/page.tsx
  front-end/src/components/Header.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/data/instructorData.js
  front-end/src/data/studentData.js
  front-end/src/data/vidListData.js
  front-end/src/redux/store.ts
  front-end/src/styles/pages/home/home.scss
  front-end/src/styles/pages/playlist/playlist.scss
  front-end/src/types/video.d.ts
  front-end/yarn.lock
Labels: ✨ Feature, 🎨 UI

#64 [FE] [#54] 챗봇 로그인 회원가입 페이지 제외 조건부 렌더링 및 초기 UI 퍼블리싱
  front-end/src/app/layout.tsx
  front-end/src/app/login/page.tsx
  front-end/src/components/Chatbot.tsx
  front-end/src/components/ChatbotLayout.tsx
  front-end/src/styles/pages/chatbot/chatbot.scss
Labels: ✨ Feature, 🎨 UI

#81 [FE] [#80] eslint 설정 값 변경
  front-end/src/app/layout.tsx
  front-end/src/app/login/page.tsx
  front-end/src/app/mypage/page.tsx
  front-end/src/app/signup/page.tsx
  front-end/src/components/ChatbotLayout.tsx
  front-end/src/components/ClientProvider.tsx
  front-end/src/components/Header.tsx
  front-end/src/redux/reducer.ts
  front-end/src/redux/store.ts
Labels: 🔧 Refactor

#82 [FE] [#37] 마이페이지 백엔드 연결
  front-end/package.json
  front-end/src/app/api/userApi.ts
  front-end/src/app/mypage/page.tsx
  front-end/src/components/ClientProvider.tsx
  front-end/src/redux/reducer.ts
  front-end/src/redux/store.ts
  front-end/yarn.lock
Labels: ✨ Feature, 🔗 API

#83 [FE] [#81] husky 값 설정 및 eslint 설정 최소화
  .husky/pre-commit
  front-end/.eslintrc.json
  front-end/package.json
  front-end/public/assets/json/videos.json
  front-end/src/app/mypage/page.tsx
  front-end/src/components/ClientProvider.tsx
  front-end/src/redux/store.ts
  front-end/src/styles/common/layout/_grid.scss
  front-end/src/styles/pages/home/home.scss
  front-end/src/styles/pages/mypage/mypage.scss
  front-end/src/styles/pages/playlist/playlist.scss
  front-end/tsconfig.json
Labels: 🔧 Refactor, 🐛 Bug

#85 [FE] [#84] 회원가입 페이지 api 요청시 오류 수정
  front-end/src/app/api/registerUserApi.ts
  front-end/src/app/mypage/page.tsx
  front-end/src/app/signup/page.tsx
  front-end/src/components/ClientProvider.tsx
  front-end/src/redux/store.ts
Labels: 🐛 Bug

#88 [BE] 유효성 검사 front로부터 예외처리 메세지, 상태를 통신할 수 있도록 코드 수정
  back-end/src/main/java/com/techie/backend/global/exception/GlobalExceptionHandler.java
Labels: 🔧 Refactor

#86 [BE] [#21] 메모 관리 기능 구현
  back-end/src/main/java/com/techie/backend/BackendApplication.java
  back-end/src/main/java/com/techie/backend/global/BaseTime.java
  back-end/src/main/java/com/techie/backend/global/config/ModelMapperConfig.java
  back-end/src/main/java/com/techie/backend/global/exception/ExceptionType.java
  back-end/src/main/java/com/techie/backend/global/exception/GlobalExceptionHandler.java
  back-end/src/main/java/com/techie/backend/global/exception/memo/EmptyContentException.java
  back-end/src/main/java/com/techie/backend/global/security/LoginFilter.java
  back-end/src/main/java/com/techie/backend/memo/controller/MemoController.java
  back-end/src/main/java/com/techie/backend/memo/domain/Memo.java
  back-end/src/main/java/com/techie/backend/memo/dto/MemoRequest.java
  back-end/src/main/java/com/techie/backend/memo/dto/MemoResponse.java
  back-end/src/main/java/com/techie/backend/memo/dto/MemoUpdateRequest.java
  back-end/src/main/java/com/techie/backend/memo/repository/MemoRepository.java
  back-end/src/main/java/com/techie/backend/memo/service/MemoService.java
  back-end/src/main/java/com/techie/backend/memo/service/MemoServiceImpl.java
  back-end/src/main/java/com/techie/backend/video/repository/VideoRepository.java
Labels: ✨ Feature

#87 [FE] [#37] 마이페이지 백엔드 기능 구현
  .husky/pre-commit
  front-end/src/app/mypage/page.tsx
  front-end/src/types/userInfo.d.ts
Labels: 🔧 Refactor, 🔗 API

#94 [FE] [#93] 유효성 검사 프론트에서 적용
  front-end/src/app/signup/page.tsx
  front-end/src/styles/pages/register/register.scss
Labels: ✨ Feature

#91 [FE] [#54] 챗봇 UI 수정
  front-end/src/app/@isLoginChatbot/page.tsx
  front-end/src/styles/pages/chatbot/chatbot.scss
Labels: 🎨 UI

#99 [FE] [#98] 메인 슬라이드 내용 3개 추가
  front-end/.eslintrc.json
  front-end/package.json
  front-end/public/assets/images/main/banner01.webp
  front-end/public/assets/images/main/banner02.webp
  front-end/public/assets/images/main/banner03.png
  front-end/public/assets/images/main/banner04.png
  front-end/src/app/page.tsx
  front-end/src/app/playlists/[category]/[videoId]/page.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/styles/pages/home/home.scss
  front-end/src/types/global.d.ts
Labels: 🎨 UI

#104 [FE] [#103] 유튜브 동영상 최신 20개 호출 / 리액트 쿼리 적용
  front-end/package.json
  front-end/public/assets/images/main/logo07.jpg
  front-end/public/assets/images/main/logo08.jpg
  front-end/public/assets/images/main/logo09.jpg
  front-end/src/app/api/teacherAPI.ts
  front-end/src/app/layout.tsx
  front-end/src/app/playlists/[category]/[videoId]/page.tsx
  front-end/src/app/playlists/page.tsx
  front-end/src/app/teacher-lists/page.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/data/instructorData.js
  front-end/src/providers/ReactQueryProvider.tsx
  front-end/src/types/video.d.ts
  front-end/yarn.lock
Labels: ✨ Feature, 🔗 API

#97 [BE] [#92] 사용자 재생목록 기능 추가 및 개선 사항
  back-end/src/main/java/com/techie/backend/global/exception/ExceptionType.java
  back-end/src/main/java/com/techie/backend/global/exception/GlobalExceptionHandler.java
  back-end/src/main/java/com/techie/backend/global/exception/playlist/InvalidVideoIdException.java
  back-end/src/main/java/com/techie/backend/global/exception/playlist/PlaylistNotFoundException.java
  back-end/src/main/java/com/techie/backend/global/exception/playlist/VideoNotFoundException.java
  back-end/src/main/java/com/techie/backend/global/exception/user/InvalidPasswordException.java
  back-end/src/main/java/com/techie/backend/global/exception/user/NoChangesException.java
  back-end/src/main/java/com/techie/backend/global/security/LoginFilter.java
  back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
  back-end/src/main/java/com/techie/backend/gpt/controller/GptController.java
  back-end/src/main/java/com/techie/backend/gpt/domain/Gpt.java
  back-end/src/main/java/com/techie/backend/gpt/service/GptServiceImpl.java
  back-end/src/main/java/com/techie/backend/memo/dto/MemoRequest.java
  back-end/src/main/java/com/techie/backend/memo/repository/MemoRepository.java
  back-end/src/main/java/com/techie/backend/playlist/controller/PlaylistController.java
  back-end/src/main/java/com/techie/backend/playlist/domain/Playlist.java
  back-end/src/main/java/com/techie/backend/playlist/dto/PlaylistRequest.java
  back-end/src/main/java/com/techie/backend/playlist/dto/PlaylistResponse.java
  back-end/src/main/java/com/techie/backend/playlist/repository/PlaylistRepository.java
  back-end/src/main/java/com/techie/backend/playlist/repository/PlaylistRepositoryCustom.java
  back-end/src/main/java/com/techie/backend/playlist/repository/PlaylistRepositoryImpl.java
  back-end/src/main/java/com/techie/backend/playlist/service/PlaylistService.java
  back-end/src/main/java/com/techie/backend/playlist/service/PlaylistServiceImpl.java
  back-end/src/main/java/com/techie/backend/playlist_video/domain/PlaylistVideo.java
  back-end/src/main/java/com/techie/backend/playlist_video/repository/PlaylistVideoRepository.java
  back-end/src/main/java/com/techie/backend/playlist_video/repository/PlaylistVideoRepositoryCustom.java
  back-end/src/main/java/com/techie/backend/playlist_video/repository/PlaylistVideoRepositoryImpl.java
  back-end/src/main/java/com/techie/backend/user/controller/UserController.java
  back-end/src/main/java/com/techie/backend/user/dto/UserRequest.java
  back-end/src/main/java/com/techie/backend/user/service/UserService.java
  back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
  back-end/src/main/java/com/techie/backend/video/domain/Video.java
  back-end/src/main/java/com/techie/backend/video/repository/VideoRepository.java
Labels: ✨ Feature, 🔧 Refactor, 🔗 API, 🐛 Bug

#107 [BE] [#96] 메모 페이징 기능 구현
  back-end/src/main/java/com/techie/backend/memo/controller/MemoController.java
  back-end/src/main/java/com/techie/backend/memo/dto/MemoRequest.java
  back-end/src/main/java/com/techie/backend/memo/dto/MemoResponse.java
  back-end/src/main/java/com/techie/backend/memo/dto/MemoUpdateRequest.java
  back-end/src/main/java/com/techie/backend/memo/repository/MemoRepository.java
  back-end/src/main/java/com/techie/backend/memo/service/MemoService.java
  back-end/src/main/java/com/techie/backend/memo/service/MemoServiceImpl.java
Labels: ✨ Feature, 🔧 Refactor

#112 [FE] [#111] 영상 검색 기능 백엔드 연결
  front-end/src/app/api/videoAPI.ts
  front-end/src/app/page.tsx
  front-end/src/components/Header.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/styles/pages/playlist/playlist.scss
Labels: ✨ Feature, 🔗 API

#106 [FE] [#105] 메모 API 연동
  front-end/src/app/api/memoAPI.ts
  front-end/src/app/playlists/[category]/[videoId]/page.tsx
  front-end/src/types/global.d.ts
  front-end/src/types/youtube.d.ts
Labels: ✨ Feature, 🔗 API

#115 [BE] [#100] 영상 응답 JSON에 videoId 추가
  back-end/src/main/java/com/techie/backend/video/dto/VideoResponse.java
  back-end/src/main/java/com/techie/backend/video/service/VideoService.java
Labels: ✨ Feature

#114 [FE] [#113] 메인 개발 항목 및 강사 리스트 json 호출 방식으로 변경
  front-end/src/app/page.tsx
Labels: 🔧 Refactor

#120 [FE] [#119] 메모 백엔드 기능 연결
  front-end/src/app/api/memoAPI.ts
  front-end/src/app/api/videoAPIDetail.ts
  front-end/src/app/layout.tsx
  front-end/src/app/playlists/[category]/[videoId]/page.tsx
  front-end/src/components/axios/apiClient.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/redux/store.ts
  front-end/src/styles/pages/playlist/playlist.scss
Labels: ✨ Feature, 🔗 API

#121 [BE] [#118] 영상 응답에 페이징 추가
  back-end/src/main/java/com/techie/backend/video/controller/VideoController.java
  back-end/src/main/java/com/techie/backend/video/service/VideoService.java
Labels: ✨ Feature

#123 [FE] [#122] 마이페이지 컴포넌트 항목들 분리
  front-end/src/app/api/memoAPI.ts
  front-end/src/app/api/userApi.ts
  front-end/src/app/api/videoAPI.ts
  front-end/src/app/api/videoAPIDetail.ts
  front-end/src/app/mypage/page.tsx
  front-end/src/app/playlists/[category]/[videoId]/page.tsx
  front-end/src/components/mypage/MyMemoSection.tsx
  front-end/src/components/mypage/MyVideoSection.tsx
  front-end/src/components/mypage/UserInfoSection.tsx
  front-end/src/styles/pages/mypage/mypage.scss
  front-end/src/types/memo.d.ts
Labels: ✨ Feature, 🔗 API

#125 [FE] [#124] 메인 화면 최신 강의 백엔드 API 연결
  front-end/src/app/page.tsx
  front-end/src/components/Header.tsx
  front-end/src/styles/pages/home/home.scss
Labels: 🔧 Refactor, 🔗 API

#133 [BE] [#132] 모든 카테고리 영상 조회해오기
  back-end/src/main/java/com/techie/backend/video/controller/VideoController.java
  back-end/src/main/java/com/techie/backend/video/service/VideoService.java
Labels: ✨ Feature

#137 [BE] [#110] 회원 정보 수정 기능 개선 및 코드 개선
  back-end/src/main/java/com/techie/backend/global/exception/ExceptionType.java
  back-end/src/main/java/com/techie/backend/global/exception/GlobalExceptionHandler.java
  back-end/src/main/java/com/techie/backend/global/exception/user/InvalidOldPasswordException.java
  back-end/src/main/java/com/techie/backend/global/exception/user/NewPasswordMisMatchException.java
  back-end/src/main/java/com/techie/backend/global/security/JWTFilter.java
  back-end/src/main/java/com/techie/backend/global/security/PathConfig.java
  back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
  back-end/src/main/java/com/techie/backend/gpt/domain/Gpt.java
  back-end/src/main/java/com/techie/backend/memo/controller/MemoController.java
  back-end/src/main/java/com/techie/backend/memo/service/MemoService.java
  back-end/src/main/java/com/techie/backend/memo/service/MemoServiceImpl.java
  back-end/src/main/java/com/techie/backend/playlist/service/PlaylistServiceImpl.java
  back-end/src/main/java/com/techie/backend/user/dto/UserRequest.java
  back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
Labels: 🔧 Refactor, 🐛 Bug

#129 [FE] [#19] 회원가입 / 로그인 페이지 퍼블리싱 수정
  front-end/src/app/login/page.tsx
  front-end/src/app/signup/page.tsx
  front-end/src/styles/pages/login/login.scss
  front-end/src/styles/pages/register/register.scss
Labels: 🎨 UI

#134 [FE] [#37] 마이페이지 정보 수정 백엔드 API 연동
  front-end/src/app/api/userApi.ts
  front-end/src/components/Header.tsx
  front-end/src/components/mypage/UserInfoSection.tsx
Labels: 🔧 Refactor, 🔗 API

#136 [FE] [#135] 백엔드 전체 유튜브 동영상 API 연결 작업
  front-end/src/app/api/videoAPI.ts
  front-end/src/app/page.tsx
  front-end/src/app/playlists/[category]/page.tsx
  front-end/src/app/playlists/page.tsx
  front-end/src/components/Header.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/data/vidListData.js
  front-end/src/styles/common/layout/_header.scss
  front-end/src/styles/pages/home/home.scss
  front-end/src/styles/pages/playlist/playlist.scss
  front-end/src/types/video.d.ts
Labels: 🔧 Refactor, 🔗 API

#140 [BE] [#139] 메모 서비스 로직 변경
  back-end/src/main/java/com/techie/backend/memo/controller/MemoController.java
  back-end/src/main/java/com/techie/backend/memo/dto/MemoResponse.java
  back-end/src/main/java/com/techie/backend/memo/service/MemoService.java
  back-end/src/main/java/com/techie/backend/memo/service/MemoServiceImpl.java
  back-end/src/main/java/com/techie/backend/video/domain/Video.java
Labels: 🔧 Refactor, 🔗 API

#142 [BE] [#141] 플레이리스트 로직 수정
  back-end/src/main/java/com/techie/backend/global/config/ModelMapperConfig.java
  back-end/src/main/java/com/techie/backend/playlist/controller/PlaylistController.java
  back-end/src/main/java/com/techie/backend/playlist/dto/PlaylistRequest.java
  back-end/src/main/java/com/techie/backend/playlist/dto/PlaylistResponse.java
  back-end/src/main/java/com/techie/backend/playlist/service/PlaylistService.java
  back-end/src/main/java/com/techie/backend/playlist/service/PlaylistServiceImpl.java
  back-end/src/main/java/com/techie/backend/playlist_video/repository/PlaylistVideoRepositoryCustom.java
  back-end/src/main/java/com/techie/backend/playlist_video/repository/PlaylistVideoRepositoryImpl.java
  back-end/src/main/java/com/techie/backend/video/domain/Video.java
  back-end/src/main/java/com/techie/backend/video/service/VideoService.java
Labels: 🔧 Refactor

#149 [BE] [#148] 영상 제목까지 저장하도록 수정
  back-end/src/main/java/com/techie/backend/memo/service/MemoServiceImpl.java
  back-end/src/main/java/com/techie/backend/video/controller/VideoController.java
  back-end/src/main/java/com/techie/backend/video/domain/Video.java
Labels: 🔧 Refactor

#144 [FE] [#91] 챗봇 초기 위치 수정
  front-end/src/app/@isLoginChatbot/page.tsx
Labels: 🔧 Refactor, 🎨 UI

#143 [FE] [#138] 메모 기능 오류 수정 및 레이아웃 일부 변경
  front-end/src/components/mypage/MyMemoSection.tsx
  front-end/src/styles/pages/mypage/mypage.scss
  front-end/src/styles/pages/playlist/playlist.scss
Labels: 🔧 Refactor

#147 [FE] [#146] 강사 리스트 메모 기능 연결
  front-end/src/app/api/teacherAPI.ts
  front-end/src/app/teacher-lists/[category]/[videoId]/page.tsx
  front-end/src/app/teacher-lists/[category]/page.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/data/instructorData.js
  front-end/src/types/video.d.ts
Labels: ✨ Feature, 🔗 API

#154 [BE] [#144] playlistDetails 코드 수정
  back-end/src/main/java/com/techie/backend/playlist/controller/PlaylistController.java
  back-end/src/main/java/com/techie/backend/playlist/service/PlaylistService.java
  back-end/src/main/java/com/techie/backend/playlist/service/PlaylistServiceImpl.java
Labels: 🐛 Bug

#153 [FE] [#145] 플레이리스트 API 연동
  back-end/build.gradle
  back-end/src/main/java/com/techie/backend/playlist/controller/PlaylistController.java
  back-end/src/main/java/com/techie/backend/video/controller/VideoController.java
  front-end/src/app/@isLoginChatbot/page.tsx
  front-end/src/app/api/playlistApi.ts
  front-end/src/app/my-video-list/playlistId/[playlistId]/page.tsx
  front-end/src/components/mypage/MyVideoSection.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/styles/pages/my-video-list/my-video-list.scss
  front-end/src/styles/pages/mypage/mypage.scss
  front-end/src/styles/pages/playlist/playlist.scss
  front-end/src/types/playlist.d.ts
Labels: ✨ Feature, 🔗 API

#159 [FE]환경변수 수정
  front-end/src/app/api/playlistApi.ts
Labels: 🔧 Refactor

#160 [FE] 플레이리스트 오류 수정 / 챗봇 오류 수정
  front-end/src/app/@isLoginChatbot/page.tsx
  front-end/src/app/api/playlistApi.ts
Labels: 🔧 Refactor

#161 [FE] e.preventDefault(); 위치 수정
  front-end/src/app/@isLoginChatbot/page.tsx
Labels: 🔧 Refactor

#162 [FE] [#116] 강사별 리스트 ALL 카테고리 오류 수정
  front-end/src/app/@isLoginChatbot/page.tsx
  front-end/src/app/page.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/styles/pages/mypage/mypage.scss
  front-end/src/styles/pages/playlist/playlist.scss
Labels: 🐛 Bug

#167 [FE] 타입 지정 오류 해결
  front-end/src/app/playlists/[category]/[videoId]/page.tsx
  front-end/src/app/teacher-lists/[category]/[videoId]/page.tsx
Labels: 🐛 Bug

#168 [FE] UseEffect 의존성 배열에 Token값 추가
  front-end/src/app/my-video-list/playlistId/[playlistId]/page.tsx
  front-end/src/components/mypage/MyVideoSection.tsx
Labels: 🐛 Bug

#170 [FE] 빌드시 발생하는 의존성 배열 오류 해결
  front-end/src/app/my-video-list/playlistId/[playlistId]/page.tsx
  front-end/src/components/mypage/MyVideoSection.tsx
Labels: 🐛 Bug
