Repository techieOrganization/techie, pull requests merged in 2024-12, with the labels that each got.

#172 [FE] 8080 포트 주소 변경
  front-end/src/components/axios/apiClient.tsx
Labels: 🔗 API

#178 [FE] [#176] 1차 배포 후 프론트 기능 및 레이아웃 리팩토링
  .idea/.gitignore
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/techie.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  back-end/src/main/java/com/techie/backend/global/security/PathConfig.java
  back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
  front-end/.husky/pre-commit
  front-end/src/app/favicon.ico
  front-end/src/app/globals.css
  front-end/src/components/Header.tsx
  front-end/src/components/axios/apiClient.tsx
  front-end/src/components/memo/ConfirmModal.tsx
  front-end/src/components/memo/MemoForm.tsx
  front-end/src/components/memo/MemoList.tsx
  front-end/src/components/mypage/MyMemoSection.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/hooks/memo/useInfiniteScroll.ts
  front-end/src/hooks/memo/useMemos.ts
  front-end/src/hooks/memo/useYouTubePlayer.ts
  front-end/src/hooks/playlist/useInfiniteScroll.ts
  front-end/src/styles/pages/playlist/playlist.scss
  front-end/src/utils/memo/timeUtils.ts
  front-end/src/utils/playlist/formatDuration.ts
Labels: 🔧 Refactor

#179 [FE] [#176] 메모 페이지 수정
  front-end/src/app/playlists/[category]/[videoId]/page.tsx
  front-end/src/app/teacher-lists/[category]/[videoId]/page.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
Labels: 🔧 Refactor

#181 [FE][#176] 1차 배포 이후 QA 반영 프론트엔드 변경사항
  .vscode/launch.json
  front-end/src/app/@isLoginChatbot/page.tsx
  front-end/src/app/api/playlistApi.ts
  front-end/src/app/login/page.tsx
  front-end/src/app/my-video-list/playlistId/[playlistId]/page.tsx
  front-end/src/components/mypage/MyVideoSection.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/styles/pages/chatbot/chatbot.scss
  front-end/src/styles/pages/my-video-list/my-video-list.scss
  front-end/src/styles/pages/mypage/mypage.scss
Labels: 🔧 Refactor

#182 [FE] [#183][#184]재생목록 내 개별 영상 삭제 기능구현 / 빈 재생목록 생성 불가 / 사용자경험 측면 alert 창 삭제
  front-end/src/app/api/playlistApi.ts
  front-end/src/app/my-video-list/playlistId/[playlistId]/page.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/styles/pages/my-video-list/my-video-list.scss
Labels: ✨ Feature

#185 [FE] 마이페이지 내 재생목록 삭제 기능 추가
  front-end/src/components/mypage/MyVideoSection.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/styles/pages/my-video-list/my-video-list.scss
  front-end/src/styles/pages/mypage/mypage.scss
  front-end/src/styles/pages/playlist/playlist.scss
Labels: 🔧 Refactor

#189 [FE] [#188] console.error 유틸리티 함수 분리
  front-end/src/app/@isLoginChatbot/page.tsx
  front-end/src/app/api/playlistApi.ts
  front-end/src/app/api/teacherAPI.ts
  front-end/src/app/api/videoAPI.ts
  front-end/src/app/api/videoAPIDetail.ts
  front-end/src/app/api/youtubeAPI.ts
  front-end/src/app/login/page.tsx
  front-end/src/app/my-video-list/playlistId/[playlistId]/page.tsx
  front-end/src/app/page.tsx
  front-end/src/app/playlists/[category]/[videoId]/page.tsx
  front-end/src/app/signup/page.tsx
  front-end/src/app/teacher-lists/[category]/[videoId]/page.tsx
  front-end/src/components/mypage/MyMemoSection.tsx
  front-end/src/components/mypage/MyVideoSection.tsx
  front-end/src/components/mypage/UserInfoSection.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/hooks/memo/useMemos.ts
  front-end/src/hooks/memo/useYouTubePlayer.ts
  front-end/src/styles/pages/mypage/mypage.scss
  front-end/src/utils/logger.ts
Labels: 🔧 Refactor, 🐛 Bug

#191 [FE] [#192] cross-spawn
  front-end/package.json
  front-end/yarn.lock
Labels: 🐛 Bug

#193 [FE] 타입 에러 오류 수정
  front-end/src/app/my-video-list/playlistId/[playlistId]/page.tsx
  front-end/src/app/playlists/[category]/[videoId]/page.tsx
  front-end/src/app/teacher-lists/[category]/[videoId]/page.tsx
  front-end/src/components/mypage/MyVideoSection.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/utils/logger.ts
Labels: 🐛 Bug

#194 [FE] 1차 배포 후 프론트 QA 반영 및 타입 에러 수정
  front-end/package.json
  front-end/src/app/my-video-list/playlistId/[playlistId]/page.tsx
  front-end/src/app/playlists/[category]/[videoId]/page.tsx
  front-end/src/app/teacher-lists/[category]/[videoId]/page.tsx
  front-end/src/components/mypage/MyVideoSection.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/utils/logger.ts
  front-end/yarn.lock
Labels: 🐛 Bug

#198 [BE] AWS EC2 HealthCheck용 컨트롤러 생성
  back-end/src/main/java/com/techie/backend/global/AwsHealthCheck.java
Labels: 🚀 Deploy

#196 [BE] [FE] README 파일 수정
  README.md
Labels: 📄 Docs

#200 [FE] [#195] 메인 반응형 작업
  front-end/src/app/page.tsx
  front-end/src/styles/common/abstracts/_responsive.scss
  front-end/src/styles/common/layout/_grid.scss
  front-end/src/styles/common/layout/_header.scss
  front-end/src/styles/pages/home/home.scss
Labels: 🎨 UI

#202 [FE][#203] 재생목록 내 영상이 존재할 때 500번 에러 핸들링
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/styles/pages/mypage/mypage.scss
Labels: 🔧 Refactor
