Repository techieOrganization/techie, pull requests merged in 2025-03, with the labels that each got.

#231 [FE] [#230] 커뮤니티 게시판 기능 추가(나의 게시글 조회, 다른 유저 게시글 조회)
  front-end/package.json
  front-end/src/app/mypage/page.tsx
  front-end/src/app/posts/nickname/[nickname]/page.tsx
  front-end/src/app/posts/page.tsx
  front-end/src/components/mypage/MyPostsSection.tsx
Labels: ✨ Feature, 🔗 API

#232 [BE] 게시글 응답 DTO 수정 및 예외 처리
  back-end/src/main/java/com/techie/backend/board/dto/PostResponse.java
  back-end/src/main/java/com/techie/backend/board/service/PostService.java
Labels: 🔗 API

#228 [FE] [#229]프론트엔드 리팩토링
  front-end/src/app/@isLoginChatbot/page.tsx
  front-end/src/app/api/playlistApi.ts
  front-end/src/app/gpt-histories/page.tsx
  front-end/src/app/login/page.tsx
  front-end/src/app/memo/page.tsx
  front-end/src/app/posts/[id]/edit/page.tsx
  front-end/src/app/posts/page.tsx
  front-end/src/app/search-histories/page.tsx
  front-end/src/app/signup/page.tsx
  front-end/src/app/watch-histories/page.tsx
  front-end/src/components/authservice/authservice.tsx
  front-end/src/components/authservice/registerservice.tsx
  front-end/src/components/chatbot/chatLog.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/CategoryTabs.tsx
  front-end/src/components/playlist/Modal.tsx
  front-end/src/components/playlist/VideoItem.tsx
  front-end/src/components/playlist/VideoList.tsx
Labels: 🔧 Refactor
