Repository techieOrganization/techie, pull requests merged in 2025-02, with the labels that each got.

#221 [FE] [#220] gnb 스타일링 오류 수정
  front-end/src/styles/common/layout/_header.scss
Labels: 🎨 UI

#223 [FE] [#222] 커뮤니티 게시판 작업
  front-end/src/app/posts/[id]/edit/page.tsx
  front-end/src/app/posts/[id]/page.tsx
  front-end/src/app/posts/new/page.tsx
  front-end/src/app/posts/page.tsx
  front-end/src/components/Header.tsx
  front-end/src/styles/common/layout/_header.scss
Labels: ✨ Feature, 🔗 API

#224 [BE] [#225] 작성자 기준 게시글 검색 추가
  back-end/src/main/java/com/techie/backend/board/controller/PostController.java
  back-end/src/main/java/com/techie/backend/board/repository/PostRepository.java
  back-end/src/main/java/com/techie/backend/board/service/PostService.java
Labels: ✨ Feature

#227 [BE] 잘못된 요청 경로 수정
  back-end/src/main/java/com/techie/backend/board/controller/PostController.java
Labels: 🔗 API, 🐛 Bug

#226 [FE] [#222] 커뮤니티 게시글 조회, 검색, 글쓰기 기능 추가
  front-end/package.json
  front-end/src/app/api/postAPI.ts
  front-end/src/app/posts/[id]/edit/page.tsx
  front-end/src/app/posts/[id]/page.tsx
  front-end/src/app/posts/new/page.tsx
  front-end/src/app/posts/page.tsx
  front-end/src/styles/pages/post/post.scss
Labels: ✨ Feature, 🔗 API

#218 [FE][#219] 챗봇 반응형 / 재생목록 반응형 설계
  front-end/src/app/@isLoginChatbot/page.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
  front-end/src/styles/pages/chatbot/chatbot.scss
  front-end/src/styles/pages/my-video-list/my-video-list.scss
  front-end/src/styles/pages/mypage/mypage.scss
  front-end/src/styles/pages/playlist/playlist.scss
Labels: 🎨 UI
