Repository techieOrganization/techie, pull requests merged in 2025-04, with the labels that each got.

#239 [FE] [#238] axios 인스턴스 적용
  front-end/src/app/api/playlistApi.ts
  front-end/src/app/login/page.tsx
  front-end/src/components/playlist/CategoryPlaylist.tsx
  front-end/src/components/playlist/Modal.tsx
  front-end/src/components/playlist/TeacherPlaylist.tsx
Labels: 🔧 Refactor

#235 [FE] [#234] 게시글 수정/삭제 기능 추가
  front-end/src/app/api/postAPI.ts
  front-end/src/app/posts/[id]/edit/page.tsx
  front-end/src/app/posts/[id]/page.tsx
  front-end/src/app/posts/page.tsx
Labels: ✨ Feature, 🔗 API

#243 [FE] [#242] 네이버 , 구글 소셜 로그인 기능 구현
  .vscode/settings.json
  front-end/public/assets/images/main/googleIcon.png
  front-end/src/app/api/socialLoginApi.ts
  front-end/src/app/login/page.tsx
  front-end/src/app/socialLoginCallback/page.tsx
  front-end/src/components/authservice/AuthLogin.tsx
  front-end/src/components/axios/socialLogin.tsx
  front-end/src/styles/pages/login/login.scss
Labels: ✨ Feature
