Repository techieOrganization/techie, pull requests merged in 2025-01, with the labels that each got.

#205 [FE][#206] 메타데이터 설정
  front-end/src/app/favicon.ico
  front-end/src/app/layout.tsx
  front-end/src/components/Header.tsx
Labels: ⚙️ Setup

#204 [FE][#195] 로그인 / 회원가입 / 챗봇 반응형
  front-end/src/app/@isLoginChatbot/page.tsx
  front-end/src/app/@isLogoutChatbot/page.tsx
  front-end/src/app/signup/page.tsx
  front-end/src/styles/common/abstracts/_responsive.scss
  front-end/src/styles/pages/chatbot/chatbot.scss
  front-end/src/styles/pages/login/login.scss
  front-end/src/styles/pages/register/register.scss
Labels: 🎨 UI

#212 [BE] [#210] 커뮤니티 게시글 기능
  .idea/.gitignore
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/techie.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  back-end/build.gradle
  back-end/src/main/java/com/techie/backend/board/controller/PostController.java
  back-end/src/main/java/com/techie/backend/board/domain/Post.java
  back-end/src/main/java/com/techie/backend/board/domain/PostCategory.java
  back-end/src/main/java/com/techie/backend/board/dto/PostRequest.java
  back-end/src/main/java/com/techie/backend/board/dto/PostResponse.java
  back-end/src/main/java/com/techie/backend/board/repository/PostRepository.java
  back-end/src/main/java/com/techie/backend/board/service/PostService.java
  back-end/src/main/java/com/techie/backend/board/service/PostServiceImpl.java
  back-end/src/main/java/com/techie/backend/global/exception/GlobalExceptionHandler.java
  back-end/src/main/java/com/techie/backend/global/mapper/PostMapper.java
  back-end/src/main/java/com/techie/backend/memo/service/MemoServiceImpl.java
  back-end/src/main/java/com/techie/backend/user/service/UserService.java
  back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
Labels: ✨ Feature

#213 [BE] [#208] 커뮤니티 댓글 기능
  back-end/src/main/java/com/techie/backend/comment/controller/CommentController.java
  back-end/src/main/java/com/techie/backend/comment/domain/Comment.java
  back-end/src/main/java/com/techie/backend/comment/dto/CommentRequest.java
  back-end/src/main/java/com/techie/backend/comment/dto/CommentResponse.java
  back-end/src/main/java/com/techie/backend/comment/repository/CommentRepository.java
  back-end/src/main/java/com/techie/backend/comment/repository/CommentRepositoryCustom.java
  back-end/src/main/java/com/techie/backend/comment/repository/CommentRepositoryImpl.java
  back-end/src/main/java/com/techie/backend/comment/service/CommentService.java
  back-end/src/main/java/com/techie/backend/comment/service/CommentServiceImpl.java
  back-end/src/main/java/com/techie/backend/global/mapper/CommentMapper.java
Labels: ✨ Feature

#215 [BE] [#214] Service 인터페이스 제거 및 Service 클래스 구조로 통합
  back-end/src/main/java/com/techie/backend/comment/controller/CommentController.java
  back-end/src/main/java/com/techie/backend/comment/service/CommentService.java
  back-end/src/main/java/com/techie/backend/comment/service/CommentServiceImpl.java
  back-end/src/main/java/com/techie/backend/gpt/service/GptService.java
  back-end/src/main/java/com/techie/backend/gpt/service/GptServiceImpl.java
  back-end/src/main/java/com/techie/backend/playlist/service/PlaylistService.java
  back-end/src/main/java/com/techie/backend/playlist/service/PlaylistServiceImpl.java
  back-end/src/main/java/com/techie/backend/user/service/UserService.java
  back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
Labels: 🔧 Refactor

#211 [FE][#91] 챗봇 ui 수정
  front-end/src/app/@isLoginChatbot/page.tsx
  front-end/src/styles/pages/chatbot/chatbot.scss
Labels: 🔧 Refactor, 🎨 UI
